### ISSUE TITLE
Nemeth bugs with omission represented by '?'

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#103]
Making this its own issue -- comes from https://github.com/NSoiffer/MathCAT/issues/100#issuecomment-1505848549. See rule 57/p70 about omission symbols.

Speaking of general omission, it seems like this might be missing from
MathCAT. This comes up a lot in lower grades. I don't know how relevant
this is for your work.

Here's more Equatio MathML for the expression 92 ÷ 2 = ?
```
<math>
  <mn>92</mn>
  <mo>&#xF7;</mo>
  <mn>2</mn>
  <mo>=</mo>
  <mo>?</mo>
</math>
```
Here's the MathCAT braille output.
⠼⠔⠆⠨⠌⠆⠀⠨⠅⠸⠦
The final two characters should be a space and a full cell (ASCII is =)

For the expression 6 + ? = 15
```
<math>
  <mn>6</mn>
  <mo>+</mo>
  <mo>?</mo>
  <mo>=</mo>
  <mn>15</mn>
</math>
```
⠼⠖⠬⠸⠦⠀⠨⠅⠀⠼⠂⠢
Here the spacing is correct, but the ASCII characters _8 should be =

**Comment by NSoiffer** [comment]
Thanks for spotting that. Looking at the code, I didn't implement rule Rule X -- Omissions (57, p70).  There are many rules I skipped because I thought them unlikely to occur when using MathML (e.g., abbreviations). And there are rules like omissions that I just missed.

After my fix, I get
`⠼⠔⠆⠨⠌⠆⠀⠨⠅⠿`
 for the first example and 
`⠼⠖⠬⠿⠀⠨⠅⠀⠼⠂⠢`
for the second example. @mcantino1: are those correct?

The Nemeth book has an example [57(3)]: `7×2 ? 14`. That requires AT to not only know that '?' represents an operator, but that it represents `=` and therefore must space differently than if it were `×`, etc. That's definitely a stretch for AT to get right!

I'll update the demo page in a few days after I fix a few other bugs.

**Comment by mcantino1** [comment]
Hi Neil,
The general omission symbol is correct, but the spacing around the = symbol
is not correct. In Nemeth, signs of comparison always have spaces on either
side. So ⠼⠔⠆⠨⠌⠆⠀⠨⠅⠿ should be ⠼⠔⠆⠨⠌⠆⠀⠨⠅ ⠿. I believe the same rule is used
in UEB, though the UEB technical manual
<https://iceb.org/guidelines_for_technical_material_2014.pdf> (1.1.2) isn't
as clear as the Nemeth manual. Nemeth is the default code in Oregon, so I'm
much more familiar with the Nemeth rules. I've started learning UEB
technical for a couple projects I'm working on.

The example you gave of the omission symbol replacing a comparison symbol
does seem like the trickiest to resolve. I'm not sure how the AT would
determine what the omission symbol is meant to be replacing. Good luck!

Michael

**Comment by NSoiffer** [comment]
Thanks for spotting that. I should look more closely at the output -- I saw the omission symbol replaced the `?` and moved on without paying attention to the spacing. MathCAT will do the spacing correctly (even when adorned). The problem here is that the symbol to right in the MathML of the equals is `?`, which is a punctuation symbol and hence shouldn't be spaced. I have to figure a way to get the rule that substitutes the omission symbol for the `?` to interact with the rule for comparison operators.

A have a few ideas on how to make this work, but I need to think about which is the cleanest way.
