### ISSUE TITLE
Feature request: move to previous/next table-like object and maintain row/column

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#105]
A user requested this feature which seems useful with dealing with matrices.  There are a number of[ examples near the bottom of this page](http://brandonspublicfiles.s3-website-us-west-1.amazonaws.com/math_examples/09%20ANOVA.htm)  where first moving right and preserving the current row makes sense. For the matrix multiplication, you want to move right and preserve the column.

I'm not sure what key commands make sense to associate with this functions. Maybe:
* xxx-left/right arrow is 'preserve row number' (moving previous/next)
* xxx-up/down arrow is 'preserve column number' (moving previous/next).

The various combinations of shift/ctrl arrow are already in use. Maybe 'alt+ctrl' if it doesn't conflict with system commands???

**Comment by brunoprietog** [comment]
Nice. NVDA uses alt+ctrl to move through cell tables, it would be a very intuitive command in my opinion, much more than the current way. Reading matrices is quite confusing right now

**Comment by NSoiffer** [comment]
I can change it from ctrl+arrow to crl+alt+arrow. Do you know what is used in JAWS? In VoiceOver? Is there any consistency?

**Comment by brunoprietog** [comment]
It's also used in JAWS. In Voiceover, Voiceover commands are most often used to navigate through tables. On Windows, NVDA, JAWS and Narrator uses the same table navigation commands, so in my opinion it is quite consistent

**Comment by NSoiffer** [comment]
Thanks for the input. I'll make the change.

If you spot other key bindings that would be more consistent with screen readers, please let me know.

**Comment by NSoiffer** [comment]
@brunoprietog: please give[ this MathCAT NVDA build ](https://drive.google.com/file/d/1enIAzcc6Qa1J7ZPmAG0QNRBeWY4GLdIl/view?usp=drive_link) a try.

**Comment by brunoprietog** [comment]
Nice! It's much more convenient to navigate matrices now. Perhaps an improvement could be to allow using these navigation commands when hearing that there is a matrix, without having to enter it with down arrow. This would allow pressing right arrow to go to another matrix quickly, and ideally the last cell of the matrix where the user had left off could be retained. Then, a user could easily move from one matrix to another, for example, to read or understand matrix operations faster

**Comment by NSoiffer** [comment]
MathCAT has 10 placeholders that allow you to mark you location and easily move to or read (without moving) what is at that location. See the [navigation doc](https://nsoiffer.github.io/MathCAT/nav-commands.html) for the key bindings/possibilities. The limitation is that the location has to be in the same expression. That will happen in a matrix multiply example. What won't work is if two matrices are in separate locations on the page and you want to see how each entry differs.

**Comment by brunoprietog** [comment]
Oh, I hadn't read the documents! I've discovered new things. Very cool
