### ISSUE TITLE
Verbose settings of ClearSpeak and SimpleSpeak output for blindness do not announce "end matrix" nor "end determinant"

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#111]
If the intent is to use words instead of pauses to disambiguate expressions in the verbose settings of ClearSpeak and SimpleSpeak when output for blindness, should words be used to indicate the end of matrices and other named rectangular arrangements of elements into rows and columns (e.g.: "end matrix", "end determinant", etc.)?

For example, when encountering:
![image](https://github.com/NSoiffer/MathCAT/assets/117550/16e3a77a-e49f-41c3-a64d-ed943ee2bd76)
 ```tex
T(A)=\left[\begin{array}{ll}
1 & 1 \\
2 & 2
\end{array}\right] A
```

MathCAT Demo (using v0.2.5) ClearSpeak Verbose appears to depend on a subtle difference in timing between matrix elements and content that comes after the matrix:

```text
t of a, is equal to; the 2 by 2 matrix; row 1; 1, 1; row 2; 2, 2; a
```

Likewise, when encountering:
![image](https://github.com/NSoiffer/MathCAT/assets/117550/54369564-58af-41bf-85d4-8d15195d10ce)

```tex
 \begin{vmatrix}
        \mathbf{i} & \mathbf{j} & \mathbf{k} \\
        \frac{\partial X}{\partial u} & \frac{\partial Y}{\partial u} & 0 \\
        \frac{\partial X}{\partial v} & \frac{\partial Y}{\partial v} & 0 \\
 \end{vmatrix} A
```

MathCAT Demo (using v0.2.5) ClearSpeak Verbose did not announce the end of the determinant:

```text
the 3 by 3 determinant; row 1; column 1; bold i, column 2; bold j, column 3; bold k; row 2; column 1; the fraction with numerator; partial derivative    x; and denominator partial derivative u; end fraction; column 2; the fraction with numerator; partial derivative    y; and denominator partial derivative u; end fraction; column 3; 0; row 3; column 1; the fraction with numerator; partial derivative    x; and denominator partial derivative v; end fraction; column 2; the fraction with numerator; partial derivative    y; and denominator partial derivative v; end fraction; column 3; 0;    a
```

**Comment by NSoiffer** [comment]
Fixed the ClearSpeak version with https://github.com/NSoiffer/MathCAT/commit/a1a21e204aeb7d388df261924d39ccbe5c03f8a5

**Comment by NSoiffer** [comment]
Added 'end determinant in https://github.com/NSoiffer/MathCAT/commit/9df5991a07215f9c01e0177908304babf34cbd86
