### ISSUE TITLE
Possible Missing "end sub" for terms with both a subscript and superscript in ClearSpeak/SimpleSpeak

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#139]
MathCAT 0.3.0 configured to output for blindness with ClearSpeak or SimpleSpeak set to any verbosity, the speech will include an ```end sub``` at the end of $`i_{j-2}`$, LaTeX: ```$i_{j-2}$```:
```txt
i sub j minus 2 end sub,
```
However, the "end sub" is not announced for $`i_{j-2}^k`$, LaTeX: ```$i_{j-2}^k$```:
```txt
i sub j minus 2 to the k-th power
```
Mary and I thought the output ```i sub j minus 2 to the k-th power``` sounds like $`i_{j-2^k}`$. Is that by design?

If the expression is changed to $`i_{j-2^k}`$, LaTeX: ```$i_{j-2^k}$``` the ```end sub``` returns:
```txt
i sub j minus 2 to the k-th power end sub,
```

We are wondering if there is a speech rule we are missing.

**Comment by NSoiffer** [comment]
That's a mistake on my part. My thought was that the "to the..." part acts like the "end subscript". But your example demonstrates that it doesn't.

I just looked at the ClearSpeak Rules and Preference guidelines and was surprised to see subscripts aren't mentioned except when used with some specialized notations.

I'll fix the rules.
