### ISSUE TITLE
Forward translation is dropping <mtext> blocks containing time values

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#141]
Consider the following:
<math>
    <mtext>4:30</mtext>
</math>

Using either UEB Math or Nemeth mode, I get an empty string as the computed Braille string. I suspect the string is being dropped somewhare in canonicalization, but not sure.

Also, if the <mtext> block contains a longer string which contains a time substring, the entire string is dropped.

**Comment by NSoiffer** [comment]
Interesting. It is there after after canonicalization. It seems to have something to do with the `:` but not the digits. This generates an empty string:
```
<math>
    <mtext>x:x</mtext>
</math>
```

**Comment by NSoiffer** [comment]
FYI: the problem was a rule failure -- the ":" assumed that was more there than there really was. That got masked by some code that threw the error out and replaced it with "". I fixed both the rule and changed the code so it passes errors back up the chain.
