### ISSUE TITLE
UEB: Variables flanked by an open bracket are missing grade 1 indicator

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#142]
[_Updated to put the MathML in block quotes_]

Consider the following:
```
<math>
    <mo>(</mo>
    <mi>n</mi>
    <mo>=</mo>
    <mn>7</mn>
</math>
```
Computed Braille string:
⠐⠣⠝⠀⠐⠶⠀⠼⠛

(Sorry I forgot the right paren) Anyway, the variable n should have a grade 1 indicator. This also happens with left bracket and left brace.

**Comment by NSoiffer** [comment]
This one is a little tricky to fix. I need to find out which letters need what checks to see if a G1 indicator is needed. For this example, "10.1 Alphabetic wordsigns" includes "not" and other potential problem contractions when the letter is "standing alone".

Does that or other contraction rules apply for non letters standing alone? I haven't checked to see if all the contractions are the dots used for letters or whether other signs might be involved.

**Comment by NSoiffer** [comment]
Never mind about it being tricky. I see I do have some code for this ('a', 'i', and 'o' don't have this problem), so the code is buggy. I didn't miss this case.

@rob-aph: Could you come up with some more examples that represent _different_ situations of a letter standing alone (i.e, don't just change the 'n' to a 'p' in the example you gave)? I'd like to add them to my tests.

**Comment by NSoiffer** [comment]
Sigh. Basically a typo. I added the above test but would definitely like more test cases. There aren't many in the ICEB technical guidelines.
