### ISSUE TITLE
UEB: Trouble with omega and Omega

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#145]
Lower case omega as input is producing the Braille for upper case omega. Upper case Omega as input is producing no Braille output and the following message:
REPLACE_INDICATORS and UEB_INDICATOR_REPLACEMENTS are not in sync: missing 'Ω'

**Comment by NSoiffer** [comment]
I messed up the tail end of the Greek alpha due to the var-sigma character and the fixes since have had problems :-(
