### ISSUE TITLE
UEB Math: Dot pattern for approximately equal to is incorrect

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#149]
In UEB's unicode.yaml, you have the following:
 - "≅": [t: "⠸⠔"]               # 0x2245 (Approximately equal to (tilde over equals sign))
I believe it should be:
 - "≅": [t: "⠐⠸⠔"]               # 0x2245 (Approximately equal to (tilde over equals sign))

**Comment by NSoiffer** [comment]
Thanks. Please keep an eye out for other miscodings. I don't know where I got the original list, but I don't think there were many sources that I was able to scrape, so that limits the ability to check one list against another.
