### ISSUE TITLE
UEB: Need character for ampersand

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#161]
The Braille character for ampersand, ⠈⠯, is missing.

**Comment by NSoiffer** [comment]
It is in `unicode.yaml`:
```
 - "&": [t: "⠈⠯"]               # 0x26 (Ampersand)
```

Why do you think it is missing?

FYI: `<`, `>`, and `&` are special HTML/XML characters and need to be escaped in some way in the input to MathCAT. E.g., `&amp;`. Any chance this is the problem you have?

**Comment by rob-aph** [comment]
Sorry, it was a bug in our code. Should have double-checked.
