### ISSUE TITLE
UEB Chemistry: Need symbol for quadruple line bond

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#162]
I believe U+2263 should map to ⠈⠸⠠⠤, quadruple line bond.

**Comment by rob-aph** [comment]
Looks like you missed the dot 4 at the beginning:
⠈⠸⠠⠤,

**Comment by NSoiffer** [comment]
Fixed.

FYI: feel free to fix these things yourself and submit a PR.
