### ISSUE TITLE
Not Speak multiple-row/case Equations

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#181]
With recent code, MathCAT cannot speak multiple-row/case equations such as matrix etc. Can you help double-check on it? They worked well with previous version.
An example of 2-case equation written in our editor as:
  `\case{ 3x-2y=1 \\-6x+4y=0 }`
Exported to MathML:
`<math><mrow ame-texclass="inner"><mo ame-texclass="open" fence="true" stretchy="true">{</mo><mtable align="center" displaystyle="false" columnalign="center" rowlines="none" rowspacing="0.2em" columnspacing="1em"><mtr><mtd><mrow><mn>3</mn><mi>x</mi><mo ame-texclass="bin" stretchy="false">&#x2212;</mo><mn>2</mn><mi>y</mi><mo ame-texclass="rel" stretchy="false">=</mo><mn>1</mn></mrow></mtd></mtr><mtr><mtd><mrow><mo ame-texclass="bin" stretchy="false">&#x2212;</mo><mn>6</mn><mi>x</mi><mo ame-texclass="bin" stretchy="false">+</mo><mn>4</mn><mi>y</mi><mo ame-texclass="rel" stretchy="false">=</mo><mn>0</mn></mrow></mtd></mtr></mtable><mo ame-texclass="close" fence="true" stretchy="true" symmetric="true"></mo></mrow></math>`
Many thanks

**Comment by NSoiffer** [comment]
Sorry for being slow to respond...

I just tried this with the latest MathCAT build in both SimpleSpeak and ClearSpeak (in English) and both come out ok: "2 cases, case 1; 3 x minus 2 y; is equal to 1; case 2; negative 6 x, plus 4 y; is equal to 0;"

There are some recent NVDA beta builds you can try. E.g., [here's one I make last week](https://github.com/NSoiffer/MathCATForPython/releases/download/v0.3.7-beta.4/MathCAT-0.3.7.nvda-addon). I'm going to do a "official" release soon (I'll do builds for C also). So if you find this is still a problem for you, let me know soon and give more details about the configuration you are using.
