### ISSUE TITLE
Documentation: MathCAT Settings are not in NVDA's Tools submenu

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#185]
Page containing error: https://nsoiffer.github.io/MathCAT/users.html
Relevant excerpt: "Note: in NVDA, the options can be set by using the MathCAT preferences dialog. This is accessed by going to the NVDA preferences, choosing “Tools”, and then “MathCAT settings…”."
They are in the Preferences submenu itself.

**Comment by NSoiffer** [comment]
Good catch. Now fixed.
