### ISSUE TITLE
Latency when pressing Space to read current position

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#186]
There is a distinct difference in responsiveness when I arrow around in a document containing Math or I arrow around inside a Math block VS when I press Space in a Math block to read current position. I am using Microsoft Edge 117.0.2045.47, NVDA 2023.3beta3, and and MathCAT version 0.3.6. Perhaps the implementation can be made more performant? Perhaps an extraneous pause is accidentally getting inserted before the current position is reported? This is not a large document or a large Math block or a low-spec machine. Including a log snippet below (note that I, in fact, am not using Braille and am exclusively using speech):

IO - inputCore.executeGesture (22:33:39.464) - winInputHook (9544):
Input: kb(laptop):downArrow
IO - speech.speech.speak (22:33:39.493) - MainThread (9220):
Speaking ['clickable', RateCommand(multiplier=0.56), ' ', 'lambda sub 2', ' ', RateCommand()]
IO - inputCore.executeGesture (22:33:44.421) - winInputHook (9544):
Input: kb(laptop):enter
IO - speech.speech.speak (22:33:44.443) - MainThread (9220):
Speaking ['math', CancellableSpeech (still valid)]
IO - speech.speech.speak (22:33:44.448) - MainThread (9220):
Speaking [' ', 'in base ', ' ', BreakCommand(time=257), ' ', 'lambda', ' ']
IO - braille.BrailleBuffer.update (22:33:44.451) - MainThread (9220):
Braille regions text: ['⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⠨⠇⣆', '⠨⠇⣆', '⠨⠇⣆', '⠨⠇⣆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆']
IO - braille.BrailleHandler.update (22:33:44.451) - MainThread (9220):
Braille window dots: 
IO - inputCore.executeGesture (22:33:46.895) - winInputHook (9544):
Input: kb(laptop):space
IO - speech.speech.speak (22:33:46.895) - MainThread (9220):
Speaking [BreakCommand(time=514), ' ', 'lambda', ' ']
IO - braille.BrailleBuffer.update (22:33:46.903) - MainThread (9220):
Braille regions text: ['⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⠨⠇⣆', '⠨⠇⣆', '⠨⠇⣆', '⠨⠇⣆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆', '⣨⣇⠆']
IO - braille.BrailleHandler.update (22:33:46.903) - MainThread (9220):
Braille window dots:

**Comment by NSoiffer** [comment]
Thanks for including the log. It is helpful to understand what you are doing.

I did find a misplaced `pause: long` that probably is what you have observed. I'll submit a fix and do a new build soon so you can test it.

**Comment by NSoiffer** [comment]
You can test out whether this fix works by taking [navigate.yaml.txt](https://github.com/NSoiffer/MathCAT/files/13066366/navigate.yaml.txt) and replacing navigate.yaml in
```
<home dir>/AppData/Roaming/nvda/addons/MathCAT/globalPlugins/MathCAT/Rules/Languages/en
```
with it after removing the `.txt` suffix (Github doesn't support `.yaml` files).


Let me know if you still have the delay.

**Comment by bhavyashah** [comment]
Tested the fix and it works perfectly, thanks! :)
