### ISSUE TITLE
Read exp as exponential and cov as covariance 

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#188]
MathCAT is set to medium speech amount and it does read out the trigonometric ratios in full (secant rather tahn sec).
Covariance
Example: $Cov(X+Y,X-Y)$
Currently, it says C-o-v. I'd prefer it to say "covariance" at medium and verbose and "cov" (one syllable) at terse.
Example: $f(x,y)=x \exp{-x(y+1)}$
x and exp sound too similar to me and again, I'd like it to be read as "exponential" or something like that at medium and above.

**Comment by NSoiffer** [comment]
Let me know if there are other functions that should get spoken.

Note: in your example, you have "Cov" as essentially "C", "o", "v" -- three separate variables that are presumed to be multiplied together. That won't get spoken as "Covariance" yet... #191 will clean that up.

**Comment by bhavyashah** [comment]
Makes sense, sounds good, and will report any other functions that aren't - but I feel should be - spoken out.

**Comment by NSoiffer** [comment]
FYI: this fix is in the beta I pointed you too for the latency bug.
