### ISSUE TITLE
Document copy features in documentation

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#201]
I never realized that I could press Ctrl+c when navigating a Math block to copy the Math ML code for the Math at the current position. This does not seem to be documented in either https://nsoiffer.github.io/MathCAT/nav-commands.html or https://nsoiffer.github.io/MathCAT/users.html. Also, I did not know that there were useful options that could be revealed when pressing the Applications key when simply on - not yet in navigation - a Math block. The latter seems related to MathJax and not MathCAT but might still be worth mentioning IMHO.

**Comment by NSoiffer** [comment]
I did _not_ mention MathJax because MathCAT doesn't control what it does or when it runs. MathJax can (and has) changed how it works and I don't want to have to deal with which version does what.
