### ISSUE TITLE
UEB: MathCAT should support dots over and under

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#204]
Consider the following (0.6 with a dot over the 6):
```
<math> <mn>0.</mn> <mover> <mn>6</mn> <mo>&middot;</mo> </mover> </math>
```

Computed braille string:
⠼⠚⠲⠣⠼⠋⠜⠨⠔⠐⠲
While this works, the more correct result is:
⠼⠚⠲⠣⠼⠋⠜⠘⠲

**Comment by NSoiffer** [comment]
This is sort of bad input -- there are lots of dot-like characters. This one is typically used for multiplication. If you had used "." or "˙" (U+02D9 DOT ABOVE) instead it would have worked. Any idea what software was used to generate this MathML?

I'll add this to the chars that can be a dot above.

**Comment by NSoiffer** [comment]
I would probably use U+02D9. I did a quick experiment on what MathML generators use:
* WIRIS (on line):  U+02D9
* MathJax (TeX): U+02D9
* Word Math: . (period as best I can tell)
* MathType for Word: U+02D9

Seems like there mostly agreement to use U+02D9.

**Comment by rob-aph** [comment]
Thank you, that's very helpful. I'll leave it up to you as to whether U+00b7 should remain as a possible dot above.

**Comment by NSoiffer** [comment]
I added it and don't see a reason to not permit it. If you used it, someone else might also.
