### ISSUE TITLE
UEB: Unexpected space between angle symbol and variable

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#206]
Consider the following:
```
<math> <mo>&#x2220;</mo> <mi>A</mi> <mo>&lt;</mo> <mo>&#x2220;</mo> <mi>B</mi> </math>
```

Computed braille string:
⠸⠪⠀⠠⠁⠀⠈⠣⠀⠸⠪⠠⠃

Note the space after the first angle symbol. This space should not be present. I believe it is only present when the angle symbol is the first symbol in the braille output.

**Comment by NSoiffer** [comment]
Looks like a leftover rule (that wasn't fixed) from Nemeth for prefix geometry operators. When I remove the rule, I get `⠸⠪⠠⠁⠀⠈⠣⠀⠸⠪⠠⠃`.

If that isn't correct, please reopen the issue and say what it should be (and why).
