### ISSUE TITLE
UEB braille grouping indicators missing with expression above and below

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#220]
Consider the following:
```
<math> <mover> <mi>MN</mi> <mo>&#x2194;</mo> </mover> </math>
```

Computed braille string:
⠰⠰⠠⠠⠍⠝⠨⠔⠳⠺⠗⠕

Should be:
⠰⠰⠣⠠⠠⠍⠝⠜⠨⠔⠳⠺⠗⠕

**Comment by NSoiffer** [comment]
I don't think the grouping indicators are needed for this. In 7.1, it says
> The scope of any of the four level change indicators, that is, the symbol(s) affected by it, is the next "item"
Note the word "next". It doesn't mention the preceding item.

I see only one example that doesn't have a simple base: the second example in 7.9. In that example, "lim" is not grouped.

@rob-aph: please close if you agree this is not a bug. Otherwise, let me know where it says it should be grouped.

**Comment by rob-aph** [comment]
I think the problem is a lack of good examples in your reference materials. Your limit example is interesting, and I don't know if "lim" should be groupped or not, as it is an abbreviation, and none of the reference materials address abbreviations in their discussion of what an item is.

In any case, current MathCAT output of my example would reverse translate to the following:
```
<math> <mi>M</mi> <mover> <mi>N</mi> <mo>↔</mo> </mover> </math>
```

Please see the examples in the APH UEB Math Tutorial:
https://uebmath.aphtech.org/lesson5.4

**Comment by NSoiffer** [comment]
I thought about this some more and reviewed the text. I believe you are correct that it should be grouped: GTM 12.1 uses the word "previous" -- the other text is a copy/paste issue from regular scripts.

**Comment by NSoiffer** [comment]
I'm going to make an exception to the grouping rules for "known" functions. That means "lim", "cos", etc., won't get parens. But "abs", "abc", etc., will get parens.

Does this sound reasonable? The rules seems to imply that "lim", etc., should get parens, but the example clearly contradicts that.

**Comment by rob-aph** [comment]
Yes, this sounds reasonable.
