### ISSUE TITLE
Vietnamese Chemistry Braille Signs for Bonds

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#237]
Can you please define the Braille signs for different chemistry bonds for Vietnamese  as following:
single bond: ⠤, double bond: ⠭, and triple bond: ⠿. quadrupal bond: use same as UEB. In Vietnamese, we don't have Braille for quadrupal bond.
So the test case "ethanol_bonds" has single bond, "ethylene_with_bond" has double bond.
The test case "ethylene_with_colon_bond" use colun sign to demonstrate bond. Can you please remove spaces before and after the second colon sign dots 25. There should be no spaces between colon signs used for bonds.

**Comment by NSoiffer** [comment]
I'm not at my computer at the moment.  If there is a test case,  please make sure it is correct.  If there isn't one, please add it. I'll try to make it work tomorrow.

**Comment by NSoiffer** [comment]
Please take a look at #228. There are several equilibrium arrows. Should I use those UEB encodings? If not, what should I use?

**Comment by NSoiffer** [comment]
@danghoaiphuc: I don't think this test (and comment) are correct:
```
fn ethylene_with_colon_bond() {
  let expr = "<math><mrow>
          <msub><mi>H</mi><mn>2</mn></msub><mi>C</mi>
          <mo>::</mo>
          <mi>C</mi><msub><mi>H</mi><mn>2</mn></msub>
      </mrow></math>";
  test_braille("Vietnam", expr, "⠨⠓⠢⠼⠃⠨⠉⠒⠒⠸⠉⠓⠢⠼⠃");
  // Each bond presented with column is translated with ⠒. So, triple column bonds should be ⠒⠒⠒.
```
A single colon represents a single bond, a double colon represents a double bond, and a triple colon represents a triple bond. I didn't find many sites that used this notation, but one place that does is [here](https://chem.libretexts.org/Courses/Mount_Aloysius_College/CHEM_100%3A_General_Chemistry_(O'Connor)/04%3A_Covalent_Bonding_and_Simple_Molecular_Compounds/4.04%3A_Drawing_Lewis_Structures#MULTIPLE_BONDS) (scroll down to right before the examples).

Based on your initial comment that double bonds are represented with ⠭, I think the expected output should be `⠨⠓⠢⠼⠃⠨⠉⠭⠸⠉⠓⠢⠼⠃`. Do you agree?
