### ISSUE TITLE
Subscript and superscript in Vietnamese Braille chemistry

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#238]
quite similar to math, sub and super scripts always written after its constant/variable
subscript on the left: ⠢⠞. Superscript on the left: ⠔⠞.
Subscript at the middle: ⠨⠢. Superscript at the middle: ⠨⠔.
Subscript on the right: ⠢. And superscript on the right: ⠔
Please see the test case: "beta_decay"

**Comment by NSoiffer** [comment]
@danghoaiphuc: I think that there is a mistake for the symbols for the left subscript and left superscript: 
* in the text above, it is `⠢⠞` for the subscript, and  `⠔⠞` for the superscript
* in the test "beta_decay", it is the same
* in the Word doc you sent a while back, it is (in two different locations) `⠢⠮` for the subscript, and  `⠔⠞` for the superscript (second char for subscript differs)

Which is correct? I've used what is in the Word for what I'm checking in. Please let me know if I should adjust the test or change the implementation.
