### ISSUE TITLE
Vietnamese Speech for Bond Using Colon Signs

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#239]
If it's the chemistry and uses colon to indicate bond, it should read as using dash or equal or equivalent signs of bond.
Currently, it reads as "nối đơn nối đơn" = "single bond single bond". It should speak as "nối đôi" = "double bond".
Please help check the test case "ethylene_with_colon_bond"

**Comment by NSoiffer** [comment]
I don't think anything that I did to fix the braille issues should have fixed this, but it is passing and using "nối đôi".
