### ISSUE TITLE
Vietnamese Speech For Roman Numbers in Math and Chemistry

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#240]
- In both math and chemistry, Roman numbers like I, II, III, IV etc, should be converted to speak as 1, 2, 3, 4 etc. In clearspeak style with verbose level, it's supposed to add "la mã" after speaking the number. For example: "III" should speak as "3 la mã", something equivalent to "3 roman type".
- In Chemistry, if roman numbers are written in superscript, it should be spoken as "hóa trị" = "valence".
Currently, it speaks as "mũ", that's used for logaric functions in math.
Please examine the test case "mhchem_roman_in_superscript"

**Comment by NSoiffer** [comment]
Note: the change for `Verbose` was made for both ClearSpeak and SimpleSpeak. I hope that is ok.

I added a test
```
fn roman_numeral() {
  let expr = "<math><mi>IX</mi><mo>+</mo><mi>VIII</mi><mo>=</mo><mi>XVII</mi></math>";
  test_prefs("vi", "ClearSpeak", vec![("Verbosity", "Medium")], expr, "9 cộng 8, bằng 17");
  test_prefs("vi", "ClearSpeak", vec![("Verbosity", "Verbose")], expr, "9 la mã cộng 8 la mã, bằng 17 la mã");

```
MathCAT passes this test, but if the test isn't correct, please correct it.
