### ISSUE TITLE
Tilde always spaced from operand when used as a negation operator

### ISSUE THREAD

**Issue by rob-aph** [NSoiffer/MathCAT#244]
Since tilde is considered a symbol of comparison, it is always spaced. In the following example, the spacing is undesirable:
```
<math> <mo>~</mo> <mi>p</mi> </math>
```

Is there anything that can be done about this?

**Comment by NSoiffer** [comment]
@rob-aph: can you confirm the expected output for UEB is `⠈⠔⠏`.  Can you also confirm that if the `~` is doubled, the output is `⠈⠔⠈⠔⠏`?  

Nemeth already has both forms correct. In Nemeth, a dot 5 needs to be added between the `~`s.

**Comment by rob-aph** [comment]
Yes, expected output is ⠈⠔⠏. I believe two tildes would just involve repeating the ⠈⠔.

**Comment by NSoiffer** [comment]
Great. Then I did it correctly.
