### ISSUE TITLE
Add an option to skip checking the files for updates

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#249]
Profiling shows the checking for changes in the underlying Rule files is a significant time cost -- about 40% of the time(!). 

@mwhapples, @rob-aph:  do you run braille blaster in a batch mode over a lot inputs without changing the rule files? If so, this might cut the run time in half. Is that useful?

If useful, suggestions for a preference name?  `RuleFilesAreStatic` (boolean)?

**Comment by NSoiffer** [comment]
I've implemented `CheckRuleFiles`. It can take the values:
* `All` -- check all the rule files to see if they have changed since the last call to MathCAT
* `Prefs` -- only check if either of the prefs files (`Rules/prefs.yaml` or `%AppData/MathCAT/prefs.yaml` (the user file typically set by a dialog)
* `None` -- don't check any file


Some timing tests (averaged over 1,000 times) on my Intel i7-7700K CPU (kind of old...) for setting, getting speech and braille for ${e^{ - \frac{1}{2}{{\left( {\frac{{x - \mu }}{\sigma }} \right)}^2}}}$:
* All: 4.1ms
* Prefs: 2.6ms
* None: 2.3ms

These are all after the initial load.

So there is a pretty substantial overhead to check to see if the file has been modified, although all the times are relatively small.

**Comment by NSoiffer** [comment]
I added a preference `CheckRuleFiles` which takes values:
* `All` (default): check all of the rule files used by MathCAT since the last call to MathCAT to see if they have changed. If so, re-read them.
*  `Prefs`: only check the preference files `Rules/prefs.yaml` and `%AppData%/MathCAT/prefs.yaml` (the user file typically written by a dialog)
*  `None`: don't check any file

On a Core I7-770K machine (higher end processor circa 2017), setting MathML and then getting the speech and braille for the moderate-size expression ${e^{ - \frac{1}{2}{{\left( {\frac{{x - \mu }}{\sigma }} \right)}^2}}}$ takes (averaged over 1,000 times):
* `All`: 4.2ms
* `Prefs`: 2.6ms
* `None`: 2.3ms

All the times are pretty fast, but there is a significant savings if `None` is used. It could make a difference if MathCAT is processing a lot of expressions in some batch process.

**Comment by mwhapples** [comment]
Thanks for this, it probably will impact upon BrailleBlaster performance as when translating a document settings are not expected to change between different equations in the document, so the rules probably should not be checked again. What is the default value for this preference, should we be setting it explicitly?

**Comment by NSoiffer** [comment]
Default is currently `All`, but I think I should change it to `Prefs`. For BrailleBlaster , I suspect you want `None` as neither the files in the Rules dir nor the user prefs.yaml file are going to change during a run of BrailleBlaster. However, if you do allow changes to the user prefs file while BrailleBlaster is running, then you should use `Prefs`.

Out of curiosity, when you are doing conversions, has waiting for MathCAT ever been an issue/something you wish ran faster?

**Comment by mwhapples** [comment]
We haven't identified MathCAT as the most significant bottleneck in BrailleBlaster performance. An additional consideration is that most BrailleBlaster users are probably not using math, so for them MathCAT is not a concern. However any improvements are welcome, they all will add up.
