### ISSUE TITLE
Finnish version of ASCIIMath

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#265]
Määttä Sam (CELIA) asked for a modified version of ASCIIMath for Finnish. He translated the docs and produced a unicode.yaml file and they are attached.

[Finnish STEM asciimath.docx](https://github.com/NSoiffer/MathCAT/files/15182053/Finnish.STEM.asciimath.docx)
[comparison on ASCIImath and Finnish ASCIImath.docx](https://github.com/NSoiffer/MathCAT/files/15182056/comparison.on.ASCIImath.and.Finnish.ASCIImath.docx)
[ASCIIMath-fi.zip](https://github.com/NSoiffer/MathCAT/files/15182066/ASCIIMath-fi.zip)  (unicode.yaml -- zipped because git doesn't support .yaml)

**Comment by samimaattaCelia** [comment]
I made a pull request #276 with changes to the Finnish Asciimath and I also made tests based on our specifications.

**Comment by NSoiffer** [comment]
Now part of main branch
