### ISSUE TITLE
MathCAT crashes on some MathML expressions.

### ISSUE THREAD

**Issue by jasonjgw** [NSoiffer/MathCAT#27]
To reproduce:

Using the NVDA MathCAT add-on, attempt to read a MathML expression that causes a crash.

NVDA emits an error tone, and leaves a Python traceback in the log.

Perhaps there's a separate issue for the add-on: would it be possible to log the error without causing a Python traceback (e.g., catch the error, log it and continue)? A major drawback of the current implementation is that the user can't even navigate past the problematic MathML expression to continue reading the document (e.g., with the Down-Arrow key).

The first example is taken from the Wikipedia article on the Fundamental Theorem of Calculus:
https://en.wikipedia.org/wiki/Fundamental_theorem_of_calculus

The second example appears in the Wikipedia entry on elementary algebra:
https://en.wikipedia.org/wiki/Elementary_algebra

Zip file containing instances of the MathML that crash and also the corresponding log files:
[mathcat-crashes.zip](https://github.com/NSoiffer/MathCAT/files/8446152/mathcat-crashes.zip)

**Comment by NSoiffer** [comment]
The code does catch the error, but needs to return something of the proper format that the call is expecting.
