### ISSUE TITLE
MathML causing panic, suspected cause mstyle

### ISSUE THREAD

**Issue by mwhapples** [NSoiffer/MathCAT#272]
In BrailleBlaster we have found some files not opening and the cause is MathCAT panics on some equations. It appears it may relate to a mstyle element. Here is a sample equation causing the issue (NOTE: the MathML namespace is defined further up the document tree):
`<m:math overflow="scroll"><m:mrow><m:mfrac><m:mrow><m:mrow><m:mo>(</m:mo><m:mrow><m:msup><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>6</m:mn></m:mstyle><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>9</m:mn></m:mstyle></m:msup><m:mstyle mathvariant="bold" mathsize="normal"><m:mo>&#x00D7;</m:mo></m:mstyle><m:msup><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>6</m:mn></m:mstyle><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>4</m:mn></m:mstyle></m:msup></m:mrow><m:mo>)</m:mo></m:mrow></m:mrow><m:mrow><m:msup><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>6</m:mn></m:mstyle><m:mrow><m:mstyle mathvariant="bold" mathsize="normal"><m:mn>1</m:mn><m:mn>1</m:mn></m:mstyle></m:mrow></m:msup></m:mrow></m:mfrac></m:mrow></m:math>`
The version of MathCAT in our development BrailleBlaster is commit 2fdcf2ad307e4137057e5f6f77303e08d4db81c1

**Comment by andrew-l-d** [comment]
I could not get the equation to display when disabling MathCat and using MathPlayer.  When submitting the file into which I put your equation to the [W3C New Validation Service](http://validator.w3.org/nu/) numerous errors were reported.
Andrew

**Comment by NSoiffer** [comment]
I've managed to narrow it down to this example which crashes MathCAT:
```
<math overflow="scroll">
    <msup>
        <mstyle mathvariant="bold" mathsize="normal">
            <mn>6</mn>
        </mstyle>
        <mstyle mathvariant="bold" mathsize="normal">
            <mn>9</mn>
        </mstyle>
    </msup>
</math>
```

Internally, MathCAT does some cleanup with `mstyle` and that is faulty. If one of the `mstyle`s is removed, it works. I suspect the bug has been around for a while. I hope to have a fix shortly.

**Comment by NSoiffer** [comment]
@mwhapples: any other issues that would be good to resolve before doing bumping the version number for a new build?

**Comment by mwhapples** [comment]
I am not aware of any further bugs. This though does not mean there are not more. BrailleBlaster only reports the first equation which causes a problem in the file. Also the reports come from users and they may see the math failing errors as the same and only report one even if the equations causing the issue are different. I would say bump the version number if you want to.
