### ISSUE TITLE
Feature request: Enable logs

### ISSUE THREAD

**Issue by EL-Dol** [NSoiffer/MathCAT#278]
## Feature request: Enable logs
Hi, I would request a feature to enable logs for easy debugging.
Have created a simplified version for debugging on Android at version bump to 0.6.3 and it can be found attached.

## Files
[MathCAT-4a6cf12-Added a feature to enable logs on Android.patch](https://github.com/user-attachments/files/16868260/MathCAT-4a6cf12-Added.a.feature.to.enable.logs.on.Android.patch)
[MathCATForC_enable-logs.patch](https://github.com/user-attachments/files/16868261/MathCATForC_enable-logs.patch)

**Comment by NSoiffer** [comment]
The changes seem reasonable, although I would think logging should be restricted to just the debug build.

On my windows machine, patch complains about line endings. Can you submit the changes as a PR? That would be safer.

Thanks.

**Comment by EL-Dol** [comment]
Yes, it would be nice if it was automatically enabled for debug, a bit unsure how to do that tough.
And I would love to upload all the code do a pull request, but I'm getting a permission denied when trying.

**Comment by NSoiffer** [comment]
Apologies if you already know this...

You shouldn't have a problem if you created a fork and you uploaded to your fork. So I'm guessing you just cloned MathCAT. In that case, you should be able to create a branch and do a pull request from there. I just looked and noticed I didn't have any protections on who could do what to branches. I just added a rule that limits who can push to main.

If you are still having problems, can you tell me specifically what you are doing?

**Comment by EL-Dol** [comment]
Hi, thanks for the info.
Haven't worked against public GitHub projects before, so the procedure was a bit different than what I'm used to.
There is now a merge request for MathCat about "Enable Logs" for Android.

**Comment by NSoiffer** [comment]
Merged.
