### ISSUE TITLE
All cap letters Fraction, problem with UEB Braille code

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#279]
Running develop build ver 0.6.3 of MathCAT C dll, the following fraction with all cap letters cannot be translated with UEB math Braille code. The MathML code is:
`<math><mfrac><mrow><mi>A</mi><mi>B</mi></mrow><mi>B</mi></mfrac></math>`

But mixed lower and cap letters or all in lowercase letters should be fine, like:
`<math><mfrac><mrow><mi>A</mi><mi>b</mi></mrow><mi>B</mi></mfrac></math>`

**Comment by NSoiffer** [comment]
Thanks for the short example. I can replicate this. I'll get a fix into the next build.
