### ISSUE TITLE
Overparen Function Support Request for Vietnamese

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#298]
Dear @NSoiffer 
Can you help add rule to support the translation overparen function for Vietnamese speech and Braille output as described below!
I already added "overparen" test case for both vi speech and Braille.
Code:
`
<math> <mover accent="false"> <mrow> <mi>A</mi> <mi>B</mi> </mrow> <mo accent="true">&#x23DC;</mo> </mover> </math>
`
Expected speech:

> cung a hoa, b hoa

Expected Braille:
⠫⠠⠗⠸⠁⠃
// The over paren Braille indicator ⠫⠠⠗ is placed before AB.
Many thanks.

**Comment by NSoiffer** [comment]
I added the following rule and that makes the test pass:
```
-
  name: overparen
  tag: mover
  match: "*[2][.='⏜']"
  replace:
  - t: "⠫⠠⠗"     # shape indicator, overparen
  - x: "*[1]"
```
Are there other characters above or below characters that follow a similar pattern? 

Near that rule are some rules that maybe are leftover from UEB.
* One is a rule for "angle" that matches something like: $\widehat{ABC}$
* The other is for when any of the characters `_¯→.˙~^','` appear either above or below a base. It also catches `⌒` (U+2312 : ARC) above some characters.

The second rule adds grouping chars around the base if it is not simple.

The first rule has name "angle" and the second rule has name "single-char-exceptions" if you want to look at them.

Do these rules make sense for Vietnamese or are they leftover from UEB? I couldn't find any examples that use hat, tilde, etc., in the spec you gave me in the summer.

**Comment by NSoiffer** [comment]
I added a similar test for speech. For speech, I put the translation for the over paren into `unicode_full.yaml`. Doing something similar for the braille char would be a better solution than what I did, but I don't know whether `⠫` is a generic "over" character that would be used with other similar notations (e.g., a brace over some expression) or whether an overparen is `⠫⠠⠗`. Please let me know.

**Comment by NSoiffer** [comment]
Also, I changed the braille test "meter_1" to use the new definition for `/` that you added. I hope that was correct.

You added the braille test "vi_text" that doesn't pass.:
```
  left: "⠓⠠⠹⠊⠀⠮⠰⠕⠁⠝⠀⠟⠥⠢⠁⠝⠀⠟⠥⠔⠽⠣⠞⠀⠅⠓⠔⠥⠽⠣⠞"
 right: "⠓⠠⠹⠊⠀⠮⠕⠰⠁⠝⠀⠟⠥⠢⠁⠝⠀⠟⠥⠽⠔⠣⠞⠀⠅⠓⠥⠽⠔⠣⠞"
```
"left" is the expected output, "right" is what MathCAT produced. The second word has some bad translations. Is the test wrong or is MathCAT wrong (which would mean some entries in one of the Unicode tables is wrong).

I marked the test as "ignore" so that tests pass, but it the bug  should be fixed.

Speaking of which: the speech tests need work. They are not currently part of the automatically run tests because there are too many failures... and there really should be a lot more tests. Here are the results:
```

**Comment by danghoaiphuc** [comment]
Thanks Neil a lot for adding the speech and Braille rule for overparen. It works perfect.
This is not mentioned in the Vietnamese math Braille guide. We just improve based on the requests from math teachers for the blind, who are using our software to produce Braille textbooks. So I will ask you for help if there're any new rule requests from them.

for the speech tests, I will go through and check again.

For the Vietnamese Braille text translation, I will prepare and send to you a document to describe rules for Vietnamese uncontracted Braille. Currently, MathCAT already supports to translate Vietnamese text into Braille, but not correct for rhymes with multiple vowels containing accent marks.
For instance: this "tấn", MathCAT translates ok as: ⠞⠔⠡⠝
But "tuấn", it should move the acute accent on "â" to before the vowel "u". So correct should be: ⠞⠔⠥⠡⠝
At the moment, MathCAT translates as: ⠞⠥⠔⠡⠝. It's completely understandable but not correct with Vietnamese Braille rule yet.

**Comment by NSoiffer** [comment]
Closing this issue. Please open a separate one for the text issue and include the new document.
