### ISSUE TITLE
Crash while reading a vector space-related expression.

### ISSUE THREAD

**Issue by jasonjgw** [NSoiffer/MathCAT#30]
The braille is rendered correctly, but MathCAT apparently crashes while producing the speech output.

The example is taken from
[vector-example.zip](https://github.com/NSoiffer/MathCAT/files/8465976/vector-example.zip)
https://en.wikipedia.org/wiki/Vector_space

**Comment by jasonjgw** [comment]
That's interesting: I just updated and the error still occurs. I don't know whether it's my installation, or something else. NVDA 2022.1 beta 3.
The files in the MathCAT Globalplugins\MathCAT directory have date/time stamps of today at 12:45am US eastern time, so it's looking right so far as the version goes.

**Comment by NSoiffer** [comment]
Maybe it is a difference in prefs. I tried both ClearSpeak and SimpleSpeak. Can you see if changing those makes a difference for you.

**Comment by jasonjgw** [comment]
I was using ClearSpeak rules. I changed to SimpleSpeak with the same error resulting. It's Chrome 100 on the browser side, although I don't expect that to make a difference.

**Comment by jasonjgw** [comment]
Is there an easy way to capture the settings? Or more debug output?

**Comment by NSoiffer** [comment]
The settings come from prefs.yaml. So you could send those. Preference is given to `~/AppData/Roaming/MathCAT/prefs.yaml`. If that file isn't present (it is written when you use the MathCAT settings dialog), it uses the one in the MathCAT addons folder.

I don't think you ever set this, but there is a hidden (useful for development) environment var:  `MathCATRulesDir`. You don't have that set, do you?

**Comment by NSoiffer** [comment]
I copied the prefs file and again, no problem.

I don't know of changes that I've made that should affect this, but maybe something did. I'll do another build towards the end of the day and you can try that to see if the bug is still present for you.

**Comment by NSoiffer** [comment]
Update: this is a bug in the zip library I'm using. After the file is compressed and expanded, they differ. The unix tools (and apparently the YAML reading ) report an EOF around the "bold italic rho" character. However, I've pulled  ~10 lines around the error spot and the problem remains, so it is not a single character causing the problem.

I've updated the library, but that didn't get rid of the problem. I'm exploring other compression techniques, but "Deflate" (the default) was one that didn't require separate 'C' compilation. C compilation ran into a problem finding the "clang" compiler.

**Comment by NSoiffer** [comment]
Update:
* zstd fails (even earlier)
* bzip2 works

Neither bzip2 nor zstd will compile to WASM without a C compiler properly configured, but that configuration proves elusive (for me and others who tried to build the project).

**Comment by NSoiffer** [comment]
Update:

Trying more things out, the problem seems to be with the size of the resulting file. This corresponds with the problem showing up earlier with less compression. If I remove ~1,000 lines (doesn't seem to matter which) with the highest compression, then it is fine.

I think I can change some of the alpha numeric block chars to use ranges. That would remove ~300 lines per block (600 if you count both lowercase and upper case). So just two blocks would like solve the problem.

Also, there are a lot of chars in the private use area. I think these are there because at one point in time, MathType output these chars instead of using the alphanumeric (higher plane) chars. These should go away. That alone might take me under the apparent limit.

**Comment by NSoiffer** [comment]
In looking at the issue tracker for the zip package, I saw someone else reported a similar problem. It turns out it is user-error. One needs to call `write_all` on the zip archive and not `write`. The latter is not guaranteed to write the whole file. That indeed fixes the problem.
