### ISSUE TITLE
Update for Vietnamese text Braille Translation in Equation

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#301]
Dear @NSoiffer,
I am attached here the MS Word document, describing some Vietnamese Braille translation rules for text and defining rhymes: 
[Vietnamese Uncontracted Braille Update in MathCAT.docx](https://github.com/user-attachments/files/17523944/Vietnamese.Uncontracted.Braille.Update.in.MathCAT.docx)

At the moment, MathCAT translates well rules for numbers, single letter by letter etc, but haven't supported to translate Vietnamese rhymes with two and three vowels with 5 different Vietnamese accents. Please let me know for any uncleared points in the document.
Many thanks for your support.

**Comment by NSoiffer** [comment]
I'm getting close (I think) to having the rules working. Once I get them working (hopefully by end of day tomorrow), I'll "publish" a new MathCAT and then update MathForC which will generate new DLLs.

**Comment by NSoiffer** [comment]
I have a new build here: https://github.com/NSoiffer/MathCATForC/releases/tag/v0.6.6. Let me know if you find any problems.
