### ISSUE TITLE
MathCAT not working in Chrome anymore

### ISSUE THREAD

**Issue by fcnjd** [NSoiffer/MathCAT#314]
Hi,
thank you for this cool addon, especially since it recently got LaTeX support added it started to help me out a lot.
However, since more than a week now, MathCat stopped working in chrome, e.g. on the sample from the MathCAT documentation, it just reads clickable, or mathematical when using the tab key. Speech would not be important for me at all, but Braille output is crutial, and NVDA doesn't log any errors either. Once switching to Firefox, it all works as expected. During the last days, I rebooted several times, just now moved the NVDA user folder to completely reset it and reinstalled MathCAT, or launch Chrome with extensions disabled, but nothing worked.
NVDA version 2024.4.1
Google Chrome 131.0.6778.86
Windows 10 22H2 64-Bit
I'd be very happy if you could take a look at this, as I'm normally using Chrome and just opened Firefox to try to fix this error. Yes of course this is a workaround, but I think it would be nice if it worked in all browsers.

**Comment by NSoiffer** [comment]
Something broke in Chrome and Edge with a recent update. [See the NVDA issue for a little more detail](https://github.com/nvaccess/nvda/issues/17421). I'm afraid there's nothing I can do about it. Hopefully they have a fix soon. I see they have labeled it with severity "1".
