### ISSUE TITLE
Support for MathML DTD's named entity definitions? 

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#38]
Will MathCAT be adding support for the named entity definitions in the MathML DTD (&amp;ApplyFunction;, &amp;DifferentialD;, &amp;ExponentialE;, &amp;Int;, &amp;InvisibleTimes;, &amp;PlusMinus;, etc.)?

I started creating test sets of MathML to look at the ClearSpeak and braille output compared to that produced by the SRE and noticed MathCat returns "XML parsing error at xx: {UnknownNamedReference}" when the provided MathML includes named entities.

For examples, please see: 
- https://brichwin.pages.iu.edu/tests/tests0001.html#ex59
- https://brichwin.pages.iu.edu/tests/tests0001.html#ex60
- https://brichwin.pages.iu.edu/tests/tests0001.html#ex64
- https://brichwin.pages.iu.edu/tests/tests0001.html#ex65

**Comment by NSoiffer** [comment]
No plans to support them because:
1. The XML DOM parser I have doesn't support that
2. They were deprecated in MathML 2. I think the reason was because it is not compatible with HTML. "&int;" is part of HTML, but I don't think I can make that work because the underlying library I'm using doesn't support it.

**Comment by NSoiffer** [comment]
I was wrong about '2'. They weren't deprecated but instead moved into HTML. The full list is [here](https://dev.w3.org/html5/html-author/charref). However, my first point stands -- the library I have doesn't support them. I could do a strsubstitution

**Comment by brichwin** [comment]
Confirmed working in MathCAT 0.1.23. The previous examples now render:

- https://brichwin.pages.iu.edu/tests/tests0001-0.1.23.html#ex59
- https://brichwin.pages.iu.edu/tests/tests0001-0.1.23.html#ex60
- https://brichwin.pages.iu.edu/tests/tests0001-0.1.23.html#ex64
- https://brichwin.pages.iu.edu/tests/tests0001-0.1.23.html#ex65
