### ISSUE TITLE
<mn> number values unexpectedly concatenated in Nemeth braille output from subscripts with invisible separators

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#40]
This example comes from section [3.2.5.5 Invisible operators](https://www.w3.org/TR/MathML3/chapter3.html#presm.invisibleops) of the MathML3 spec.

```xml
<math>
  <msub>
    <mi> m </mi>
    <mrow>
      <mn> 1 </mn>
      <mo> &#x2063;<!--INVISIBLE SEPARATOR--> </mo>
      <mn> 2 </mn>
    </mrow>
  </msub>
</math>
```

The MathCAT ClearSpeak and SimpleSpeak both produce usable output that separates the two number values by a space:
```
m sub 1 2
```

However, the Nemeth braille output concatenates the number values thus rendering it as m sub twelve:
```
⠍⠰⠂⠆
```

The subscript-superscript comma (dots 246), always without a following space, is used to transcribe a comma in superscripts and subscripts (See Rule XIII-[§78] on page 88 of the 1972 Nemeth Braille Code pdf).

![image](https://user-images.githubusercontent.com/117550/174163650-93bc76db-48f2-4116-86ad-6cb0346c48a2.png)
![image](https://user-images.githubusercontent.com/117550/174164406-8fde14e7-cf11-465a-a10f-45482afb1e97.png)

Thus, one could expect the following for the Nemeth braille:
```
⠍⠰⠂⠪⠆
```

**Comment by NSoiffer** [comment]
This is a little problematic for braille. There is an implied comma, but not one that is visible. Typically the braille follows what is visible so if you add a comma, it will follow the rule you mention (haven't checked this example, but I remember coding that rule). It would be simple to add that rule for invisible comma. Let me ask a Nemeth expert (Susan Osterhaus) and see what she says.

**Comment by brichwin** [comment]
I will happily defer to Susan Osterhaus.  That braille follows what is visible sounds reasonable.

**Comment by NSoiffer** [comment]
Susan said
> My Nemeth Committee loves to “follow print,” but I would want the comma to show up whether “visible” or not in print. That’s just my opinion.

I'll add the comma since I trust Susan's opinion/instinct.
