### ISSUE TITLE
Enlarged opening and closing matrix grouping symbols not indicated in Nemeth braille output.

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#41]
The MathCAT Nemeth braille output for a matrix does not indicate the enlarged open and closing grouping symbols.

For example, when provided the XML for a 3x3 identity matrix:
![image](https://user-images.githubusercontent.com/117550/174171636-0a6b7262-5415-4357-be26-c39e0d4b7890.png)

The MathCAT braille output is equivalent to "(1 0 0)(0 1 0)(0 0 1)":
```
⠷⠂⠀⠼⠴⠀⠼⠴⠾⠷⠴⠀⠼⠂⠀⠼⠴⠾⠷⠴⠀⠼⠴⠀⠼⠂⠾
```

The MathCAT speech output is recognizing the matrix:
```
the 3 by 3 matrix; column 1; 1; column 2; 0; column 3; 0; column 1; 0; column 2; 1; column 3; 0; column 1; 0; column 2; 0; column 3; 1;
```

Expected braille output:
From: The [APH Nemeth Tutorial Lesson 9.4: Matrices](https://nemeth.aphtech.org/lesson9.4):

> **Enlarged brackets**
> The enlarged brackets are three-cell symbols. Dot four is used to indicate the bracket modification; dot six, the capitalization indicator, to signify enlargement; and the opening or closing sign of grouping.
> 
> enlarged opening bracket, dot four dot six dots one two three five six
> enlarged closing bracket, dot four dot six dots two three four five six

See also, Rule XVIII-[§126] top of page 127 of the 1972 Nemeth Braille Code pdf).
![image](https://user-images.githubusercontent.com/117550/174180634-2737fbdc-ec31-4ad0-aa92-f7369ddd103d.png)

Thus, an expected Nemeth braille rendering for the above identity matrix could be:
```
⠈⠠⠷⠂⠀⠼⠴⠀⠼⠴⠈⠠⠾ ⠈⠠⠷⠴⠀⠼⠂⠀⠼⠴⠈⠠⠾ ⠈⠠⠷⠴⠀⠼⠴⠀⠼⠂⠈⠠⠾
```

To reproduce, here is the MathML (example from the MathML specification):
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <mo> ( </mo>
    <mtable>
      <mtr>
        <mtd>
          <mn>1</mn>
        </mtd>
        <mtd>
          <mn>0</mn>
        </mtd>
        <mtd>
          <mn>0</mn>
        </mtd>
      </mtr>
      <mtr>
        <mtd>
          <mn>0</mn>
        </mtd>
        <mtd>
          <mn>1</mn>
        </mtd>
        <mtd>
          <mn>0</mn>
        </mtd>
      </mtr>
      <mtr>
        <mtd>
          <mn>0</mn>
        </mtd>
        <mtd>
          <mn>0</mn>
        </mtd>
        <mtd>
          <mn>1</mn>
        </mtd>
      </mtr>
    </mtable>
    <mo> ) </mo>
  </mrow>
</math>
```
It can also be recreated using this LaTeX: 
```tex
$\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$
```

**Comment by NSoiffer** [comment]
Thanks. The code had a comment that it was using the enlarged symbols, but it actually wasn't. Plus the test for multiple rows was wrong.

In your example, you added spaces between the rows. That seems reasonable, but I don't see anything that says that is a good thing to do in the references... but of course, they all assume 2d layout. Is there any reference that says to do that?

**Comment by brichwin** [comment]
The Nemeth braille reference has strict rules for alignment of matrix rows across multiple lines. I'm guessing they didn't consider what would happen if one had to read a linearized rendering all at once from a single string. 

Mary Stores (a life long braille reader and a certified transcriber working here at Indiana University) suggested that the spaces would add readability given that each row would be in separate lines is reading an embossed version.

I hope to get her to tryout using the MathCAT equation navigation features next week.

**Comment by NSoiffer** [comment]
Thanks. I'll add the spaces.
