### ISSUE TITLE
Nemeth - Inconsistent handling of double struck letters

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#44]
For some double struck letters, like &amp;#x2147; (ExponentialE) and &amp;#x2146; (DifferentialD), the Nemeth braille output appropriately ignores the font styling:
![image](https://user-images.githubusercontent.com/117550/175186508-65282c70-e3a3-496a-b773-beab174a47c2.png)
comes out simply as `⠮⠰⠴⠘⠂⠐⠑⠘⠭⠐⠙⠭`.
<details>
  <summary>Click for the above integral's MathML source</summary>

  ```xml
  <math>
    <mrow>
      <msubsup>
        <mo> &#x222B;<--int--> </mo>
        <mn> 0 </mn>
        <mn> 1 </mn>
      </msubsup>
      <mrow>
        <msup>
          <mi> &#x2147;<--ExponentialE--> </mi>
          <mi> x </mi>
        </msup>
        <mo> &#x2062;<--InvisibleTimes--> </mo>
        <mrow>
          <mo> &#x2146;<--DifferentialD--> </mo>
          <mi> x </mi>
        </mrow>
      </mrow>
    </mrow>
  </math>
  ```
</details>

For &amp;#x2148; (ImaginaryI), the Nemeth braille output appears to be trying to indicate the special symbol:
![image](https://user-images.githubusercontent.com/117550/175187574-e7133c5f-a1e1-403a-b6b7-2a47d75f7a7a.png)
comes out as `⠼⠆⠬⠒ⅈ` (note the raw double struck italic i character in the braille output -- the braille display we tested rendered the double struck italic i as it's numeric unicode char value).
<details>
  <summary>Click for the above imaginary number's MathML source</summary>

  ```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <mn> 2 </mn>
    <mo> + </mo>
    <mrow>
      <mn> 3 </mn>
      <mo> &#x2062;<--InvisibleTimes--> </mo>
      <mi> &#x2148;<--ImaginaryI--> </mi>
    </mrow>
  </mrow>
</math>
  ```
</details>

**Comment by NSoiffer** [comment]
The char was missing from the table. It now produces `⠼⠆⠬⠒⠊` (a plain 'i' is used for the Imaginary I char)
