### ISSUE TITLE
Unexpected Nemeth output for horizontal bar in five-step rule for directly-over/under modified expressions

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#45]
The Nemeth output for directly-over and directly-under expressions modified by a horizonal bar results in "dots-36 dots-36 dots-36 dots-36" instead of simply using the Nemeth cell for horizonal bar: dots-156 (Rule XIV - Modifiers near bottom of page 98). See examples in Rule XIV Section 86 a. The Five-Step Rule for Transcribing Modified Expressions pages 99-101; Partially shown here:
![image](https://user-images.githubusercontent.com/117550/175198211-69cedaa9-85c7-44e4-9408-d16b28ea6a90.png)

For the expression: 
![image](https://user-images.githubusercontent.com/117550/175198424-39e1c9c3-621d-4de6-8c04-158414e32a49.png)
MathCat produced this Nemeth: 
`⠐⠷⠩⠤⠤⠤⠤⠀⠻⠹⠁⠌⠃⠼⠐⠾⠣⠀⠤⠤⠤⠤⠀⠻`
The expected Nemeth was:
`⠐⠷⠩⠱⠻⠹⠁⠌⠃⠼⠐⠾⠣⠱⠻` (also note no spaces between the directly-over indicator `⠣` or directly-under indicator `⠩`, the horizontal bar modifier `⠱`, and the termination indicator `⠻`)

<details>
  <summary>LaTeX and MathML Code for the above example</summary>

```tex
\underline{(}\frac{a}{b}\overline{)}
```
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true" scriptlevel="0">
    <munder>
      <mo stretchy="false">(</mo>
      <mo accent="true">&#x2015;</mo>
    </munder>
    <mfrac>
      <mi>a</mi>
      <mi>b</mi>
    </mfrac>
    <mover>
      <mo stretchy="false">)</mo>
      <mo accent="true">&#x2015;</mo>
    </mover>
  </mstyle>
</math>
```
</details>

**Comment by brichwin** [comment]
Note: for an alternate rendering of this expression, MathCAT did use the horizontal bar modifier `⠱`. See: https://github.com/NSoiffer/MathCAT/issues/46

**Comment by NSoiffer** [comment]
Currently the code considers U+2015 to be a long dash character. This is why it is `⠤⠤⠤⠤` and also has spaces around it.

I guess the code could be smarter and check to see if it is used in an munder/mover accent position and treat it as an under/over bar.
