### ISSUE TITLE
Unexpected ClearSpeak and SimpleSpeak output for variables with both a subscript and superscript

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#55]
MathCAT 0.1.23 when given the MathML for a variable with both a superscript and subscript generated unexpected ClearSpeak and SimpleSpeak output. For example,
![image](https://user-images.githubusercontent.com/117550/193472315-6453d60a-a947-4982-b1cf-af01d78566cc.png)
Generated this ClearSpeak:
`msub of, x comma k to the i-th power`
and generated this SimpleSpeak:
`msub of, x comma k to the i-th`.
We expected something more like:
`x sub k raised to the i-th power`
Here is the source MathML (generated by MathJax for `x^{i}_{k}`):
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true" scriptlevel="0">
    <msubsup>
      <mi>x</mi>
      <mrow data-mjx-texclass="ORD">
        <mi>k</mi>
      </mrow>
      <mrow data-mjx-texclass="ORD">
        <mi>i</mi>
      </mrow>
    </msubsup>
  </mstyle>
</math>
```

The settings used were:
```rust
  set_preference("TTS".to_string(), "none".to_string()).unwrap();
  set_preference("Impairment".to_string(), "Blindness".to_string()).unwrap();
  set_preference("Language".to_string(), "en".to_string()).unwrap();
  set_preference("SpeechSound".to_string(), "None".to_string()).unwrap();
  set_preference("Verbosity".to_string(), "Verbose".to_string()).unwrap();
  set_preference("MathRate".to_string(), "100".to_string()).unwrap();
  set_preference("SpeechStyle".to_string(), "ClearSpeak".to_string()).unwrap();
  set_preference("SubjectArea".to_string(), "General".to_string()).unwrap();
  set_preference("Chemistry".to_string(), "SpellOut".to_string()).unwrap();
  set_preference("BrailleCode".to_string(), "Nemeth".to_string()).unwrap();
```

**Comment by NSoiffer** [comment]
MathCAT was missing a rule. Fixed in https://github.com/NSoiffer/MathCAT/commit/6db1d5a23292e50a0f2c6cf357edc145be6b8629

For ClearSpeak, it now says "x sub k to the i-th power"
