### ISSUE TITLE
Missing speech text for "top brace" and "bottom brace" symbols

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#56]
The ClearSpeak output for math with a top or bottom brace includes the ASCII character for the symbol instead of spelling out the name of the symbol. For example, for:
![image](https://user-images.githubusercontent.com/117550/193474434-08576417-0c91-4d5e-8ef4-1384d4ddc33c.png)
MathCat 0.1.23 generated the following ClearSpeak:
```
modified x plus y plus z with ⏞ above
```
We expected something like:
```
modified x plus y plus z with top brace above
```
The MathML was:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
    <mover>
      <mrow>
        <mi>x</mi>
        <mo>+</mo>
        <mi>y</mi>
        <mo>+</mo>
        <mi>z</mi>
      </mrow>
      <mo>&#x23DE;</mo>
    </mover>
</math>
```
The bottom brace example:
![image](https://user-images.githubusercontent.com/117550/193474604-82038e01-286f-48b1-ac64-8b56bea5e1ec.png)
generated the following ClearSpeak:
```
modified x plus y plus z with ⏟ below
```
We expected something like:
```
modified x plus y plus z with bottom brace below
```

The MathML was:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
    <munder>
      <mrow>
        <mi>x</mi>
        <mo>+</mo>
        <mi>y</mi>
        <mo>+</mo>
        <mi>z</mi>
      </mrow>
      <mo>&#x23DF;</mo>
    </munder>
</math>
```

**Comment by NSoiffer** [comment]
Thanks. I've added speech for top and bottom brackets in https://github.com/NSoiffer/MathCAT/commit/82e048d6ff81f2560f8e7c54759d7ec49f047d88

My Nemeth table has those characters. Leaving open because I haven't found out yet what UEB should do with them.

**Comment by NSoiffer** [comment]
I heard back that those chars are indeed missing in UEB. They need to figure out how to add them. So closing for now.
