### ISSUE TITLE
Typo in NSoiffer/MathCAT/blob/main/Rules/prefs.yaml

### ISSUE THREAD

**Issue by brichwin** [NSoiffer/MathCAT#59]
In the prefs.yaml file, it appears to have incorrect guidance in the comments

The ClearSpeak setting on line 17 is listed as follows:
```
      Roots: Auto               # PosNegSqRoot, RootEnd, PosNegSqRootEnd
```
However, "RootEnd" has no effect. Whereas "EndRoot" seems to.

**Comment by NSoiffer** [comment]
ClearSpeak says it should be RootEnd. I will fix the code.
