### ISSUE TITLE
Improve documentation of navigation options

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCAT#74]
I will likely develop at least a partial understanding of MathCAT's navigation settings over time through usage, but upfront, I see fairly helpful explanations for all settings except those that are navigation-related on https://nsoiffer.github.io/MathCAT/users.html. In particular, some questions that remain are: how do the Enhanced, Simple, and Character navigation modes differ? What does auto-zoomout do exactly and what are 2D notations? (I tentatively recall reading something about this in the Math Player documentation.)

**Comment by NSoiffer** [comment]
The users.html page links to
https://nsoiffer.github.io/MathCAT/nav-commands.html for navigation info.
That page tries to explain what the navigation modes are and what a 2D
notation is. Did you see the page and find the explanations inadequate?

I've added more explanation for AutoZoomOut. Let me know what you think.

**Comment by bhavyashah** [comment]
Ah, thanks for pointing me to this page. On a quic skim, this looks exactly like what I was hoping for. I might still consider linking this page again at the start of the "Navigation Options" section or integrating the navigation-related documentation as part of the user guide.

**Comment by NSoiffer** [comment]
I've added the link.

I'm closing this, but feel free to reopen if you feel more work needs to be done.
