### ISSUE TITLE
Greek Letters - Wrong Braille dots

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#81]
It seems Braille dot definitions for both normal and capital Greek letters in “unicode.yaml” file are wrong:
- "ς": [t: "GL⠎"]              # 0x3c2 
 - "σ": [t: "GL⠞"]              # 0x3c3 
 - "τ": [t: "GL⠥"]              # 0x3c4 
 - "υ": [t: "GL⠋"]              # 0x3c5 
 - "φ": [t: "GL⠯"]              # 0x3c6 
 - "χ": [t: "GL⠽"]              # 0x3c7 
 - "ψ": [t: "GL⠺"]              # 0x3c8 
This might be the two sigma letters so gets the tool auto-calculated wrong
Same issue for Greek letters from line 471.

**Comment by brichwin** [comment]
I couldn't find this issue in the Nemeth and UEB folders, however the issue appears to still exist in the [Vietnam](https://github.com/NSoiffer/MathCAT/tree/main/Rules/Braille/Vietnam) folder. 

Should I work on checking the braille codes in the unicode and unicode-full files there?

**Comment by NSoiffer** [comment]
I recently [fixed this problem](https://github.com/NSoiffer/MathCAT/commit/781ab60e9d859ee5dfaed75792ab15ee87e4a6ac) which I came across when checking against the Accessible Equation Editor's list of chars. I forgot that I should make the fix in the `vi` directory also.

Note: I think
```
"ς": [t: "GL⠎"] # 0x3c2
```
is correct. The others were wrong.
