### ISSUE TITLE
Wrong Ordinary Fraction in Vietnamese

### ISSUE THREAD

**Issue by danghoaiphuc** [NSoiffer/MathCAT#84]
I cannot trace back where in Vietnamese translation language file caused the issue when reading the following expression with fractions.
`
<math><mrow><mfrac><mn>1</mn><mn>3</mn></mfrac><mo ame-texclass="bin" stretchy="false">&#x22C5;</mo><mfrac><mn>85</mn><mn>124</mn></mfrac><mo ame-texclass="bin" stretchy="false">+</mo><mfrac><mn>2</mn><mn>7</mn></mfrac><mo ame-texclass="bin" stretchy="false">&#x22C5;</mo><mfrac><mn>39</mn><mn>124</mn></mfrac><mo ame-texclass="bin" stretchy="false">+</mo><mfrac><mn>5</mn><mn>7</mn></mfrac></mrow></math>
`
The fractions 1/3 or 2/7, it should read in Vietnamese. But it read as in English as "1 third" and "two sevenths".
The file that I thought relates to this is "definitions.yaml". But I don't see any string with third or sevenths. All of them are translated into Vietnamese.
Can you help me trace for the words it takes from and fix it?
Many thanks.

**Comment by NSoiffer** [comment]
I'm not able to replicate this with the current code. I get
```
1 phần ba nhân 85 trên 124, cộng, 2 phần bảy nhân 39 trên 124, cộng 5 phần bảy
```

with both ClearSpeak and SimpleSpeak.

I'm in the process of building new NVDA addons and a C executable. Maybe try retesting with those. I'll let you know when they are available.

**Comment by danghoaiphuc** [comment]
Wow, your generated speech string is perfect. While, mine is still getting the 1 third, and 2 sevenths instead of 1 phần ba, or 2 phần bảy... Even, I already tested with latest C dll release.
Anyway, let wait to test with your new NVDA add-on.

**Comment by NSoiffer** [comment]
Is this solved with the current build? If so, please close the issue.

**Comment by danghoaiphuc** [comment]
Many thanks. It's solved.
