### ISSUE TITLE
MathCat Not Reading MathType Equations in MS Word

### ISSUE THREAD

**Issue by polizoto** [NSoiffer/MathCAT#9]
When using MathCat 0.1.2 with an MS Word document + MathType equations, MathCat will not speak the math.

Instead, I hear "graphic MathType 6.0 equation". 

E.g., The follow line from an MS Word document will read:

![image](https://user-images.githubusercontent.com/13323866/151024522-51353e5c-8d39-4806-b3f0-ff36bdc5aadd.png)

Remember, the derivative of a function "graphic MathType 6.0 equation" at a value "graphic MathType 6.0 equation" is "graphic MathType 6.0 equation".

**Note:** The version of MathType that I am using is actually 7.4.8.0 *not* 6.0

**Comment by NSoiffer** [comment]
This sounds like an error that is caused by something besides MathCAT. Try disabling MathCAT and retry reading the equation. Let me know if you still have the error or not.

**Comment by polizoto** [comment]
After disabling MathCAT, I still get the error.

I tried disabling and then enabling MathCat. I also tried reading a newly authored document with MathType 7.0. I still get the "graphic MathType 7.0 equation" output.

**Comment by NSoiffer** [comment]
By disabling MathCAT, that says the problem is not with MathCAT. It is with
NVDA or Word/MathType.

One thought: have you turned on UIA in NVDA's advanced settings? If so,
that might interfere with MathType + NVDA.

**Comment by polizoto** [comment]
That was it - I had UIA turned ON.

I am able to hear the math now. Thank you.
