### ISSUE TITLE
Make number repair follow the locale

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#91]
Right now, MathCAT goes to some length to patch up bad MathML for numbers generated by software. For example, if someone uses TeX or (most? all?) WYSIYG editors and enters `1,234`, the MathML that gets generated is:
```
<mn>1</mn><mo>,</mo><mn>234</mn>
```

That seems to work well. However, it is based on `,` being a block separator. In many parts of the world, `.` is the block separator. MathCAT needs an option so AT can tell it what convention to use. The language can't be used. The code needs to check that preference and switch `,` and `.` appropriately.

Note: the code already patches up space separators.

Another notation to consider implementing is "1`234".

**Comment by NSoiffer** [comment]
Comments from Dang Hoai Phúc re Vietnamese (where both systems are sometimes used due to heavy English influence):


1. Your idea to have DecimalSeparators and BlockSeparators sound great. for instance, in Vietnam Braille definition, we might define:

DecimalSeparators ',.'

BlockSeparators '.,'

As you see, Vietnam uses both signs for both block and decimal separators, such as: 1.234,56 and 1,234.56 are both correct. But the more priority to handle is defined first, so MathCAT should use the first sign definition then move to the next one if the first is not valid.

For example: DecimalSeparators ',.', means Vietnamese prefers to use comma to separate dec numbers first: Pi=3,14.

For English: it might be only:

DecimalSeparators '.'

BlockSeparators ','

 

For language like Spannish: I think MathCAT should give a user option to let users to choose what dec and block separators they are using. So for this option, you might also call from the definition for Spannish:

DecimalSeparators ',' '.'

BlockSeparators '.' ','

I defined two possible signs in two single quotes, different from Vietnamese definition above, because I want to mean use period or comma for dec point in Spannish. Not like in Vietnam when putting all in a single quote, could use either period or comma.

 

2. Detect decimal and block separators:

Do you have any idea to detect if it's a decimal or block separator?

Normally, in Vietnam, if written: "1234567", it's surely not having any decimal points. So we could add "period" in it by counting from the right to the left. Each block should be divided into 3 digits, so best result to output should be: "1.234.567".

If the number is: "1,234",: as in Vietnam, that number with comma should be the decimal point (1 point 2 3 4) or block separator (1 thousand 234). So, we need to have a mechanism to detect something like:

Define: DigitBlock "3" # I mean each block is set to fixed number of 3 digits for Vietnamese case.

If the number is "3.14", "3.2345" the period here is the decimalSeparators.

If the number is "1.,234.567", check from the right to the left and has both period and comma, so the period here should be decimal point while comma is the block separator.

If the number is: "1,234": in Vietnamese case, we should treat this comma as decimal separator. Because it's defined as the first priority for the DecimalSeparDecimalSeparators.

Ps: I am not sure for other languages, but in case of Vietnam, using mixed situations period sign for either block or dec separator, if MathCAT could handle this, it would give perfect result.

**Comment by NSoiffer** [comment]
I'm probably going to implement:
* DecimalSeparators: "."  # [default]
* BlockSeparators: ", \u00A0\u202F" # [default -- includes two forms of non-breaking spaces]

If there is more than one `DecimalSeparator`, the second one will be taken as something to try in limited cases where it can't be confused with one of the `BlockSeparators`. I still need to work through the details of that.

What I'm not sure about is how to determine what the values should be. Even if someone is German and would normally have
`DecimalSeparators=","` and `BlockSeparators=". "`, they might be reading a page with a different locale. Hence, it is probably best to set the locale based on the page's language. This is something MathCAT can't know, so AT needs to set it.

Note: although language usually determines the number locale, that's not always the case. For example, most Spanish speaking countries use `,` as a decimal separator, but according to [this Wikipedia page](https://en.wikipedia.org/wiki/Decimal_separator#Conventions_worldwide), many Central American countries such as Nicaragua and Panama use `.`. If the page sets the country code (e.g., "es-es" or "es-pa"), then that should be enough info to get it right. However, I think it is more common that just the language code is used, so some guessing needs to happen.

@FS-ASmith, @danghoaiphuc: does this solution seem acceptable to you?

**Comment by FS-ASmith** [comment]
Yes, I think this solution sounds very reasonable, and it would work for us.

**Comment by NSoiffer** [comment]
Fixed in 2feb6dc
