### ISSUE TITLE
MathML only containing mphantom causes a panic

### ISSUE THREAD

**Issue by mwhapples** [NSoiffer/MathCAT#96]
For MathML only containing a mphantom MathCAT will panic with an index out of bounds error. The panic message is "thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', D:\aph\projects\MathCAT4J\MathCAT\src\chemistry.rs:354:28"
Example MathML for this issue is: <m:math alttext="" altimg="images/54668-alt.png"><m:mrow class="MJX-TeXAtom-ORD"><m:mphantom><m:mspace width="2.5cm" /><m:mspace linebreak="newline" /><m:mspace width="2.5cm" /></m:mphantom></m:mrow></m:math>
This example originates from loading a nimas book (9781792463440NIMAS.zip) into a development build of BrailleBlaster.

**Comment by NSoiffer** [comment]
Thanks. I didn't guard against empty content after cleanup. Now the code does.
