### ISSUE TITLE
Fraction with empty box over empty box causes panic

### ISSUE THREAD

**Issue by mwhapples** [NSoiffer/MathCAT#97]
Another case of MathML which can cause MathCAT to panic. It appears to be a fraction with an empty box over an empty box. This example comes from a nimas book, 9781644976630NIMAS.zip
The MathML is: <m:math altimg="./images/u01/EQp009_001.jpg" alttext=""><m:mfrac><m:mrow><m:menclose notation="box"><m:mrow /></m:menclose></m:mrow><m:mrow><m:menclose notation="box"><m:mrow /></m:menclose></m:mrow></m:mfrac></m:math>

**Comment by NSoiffer** [comment]
Just to be clear, it isn't a crash, it is a failure ("no matching element") that gets caught. Is that what you see?

**Comment by mwhapples** [comment]
Yes you are correct, not actually a panic/crash but just a failure. My bad for not checking the exception message in BrailleBlaster. To allow giving the user an error message and JVM clean up I catch panics and throw an exception in (java. Crash or fail the result is the same that the book cannot be opened in BrailleBlaster.

**Comment by NSoiffer** [comment]
Both are bad, but a crash can take down the whole application, which is really, really bad. A fix is pending -- it (empty content) was an area of cleanup that I should have caught. I'm trying to improve the speech for empty content (not just with `menclose`). It will now say something like "the fraction with numerator empty box and denominator empty box".
