### ISSUE TITLE
More MathML causing a Pattern match/replacement failure

### ISSUE THREAD

**Issue by mwhapples** [NSoiffer/MathCAT#98]
I have found another example where MathML causes a "Pattern match/replacement failure" Unfortunately this time the MathML snippet is quite large, I have been unable to find the specific fragment in the equation causing the problem, hopefully the error messages will help guide you to the problem. Again comes from an actual example nimas book 9781644976609NIMAS.zip and yes I do see areas where the MathML should be done better.
The MathML: <m:math altimg="./images/u01/EQp042_002.jpg" alttext=""><m:mrow><m:mtable columnalign="right"><m:mtr columnalign="right"><m:mtd columnalign="right"><m:mrow><m:mn>5</m:mn><m:mtext> </m:mtext><m:mn>4</m:mn><m:mo>,</m:mo><m:mn>9</m:mn><m:mtext> </m:mtext><m:mn>6</m:mn><m:mtext> </m:mtext><m:mn>7</m:mn></m:mrow></m:mtd></m:mtr><m:mtr columnalign="right"><m:mtd columnalign="right"><m:mrow><m:munder accentunder="true"><m:mrow><m:mo>×</m:mo><m:mspace width="4.2em" /><m:mn>9</m:mn></m:mrow><m:mo stretchy="true">¯</m:mo></m:munder></m:mrow></m:mtd></m:mtr><m:mtr columnalign="right"><m:mtd columnalign="right"><m:mrow><m:mover><m:mspace height="1em" /><m:mn>6</m:mn></m:mover><m:mtext> </m:mtext><m:mn>3</m:mn></m:mrow></m:mtd></m:mtr></m:mtable></m:mrow></m:math>

**Comment by NSoiffer** [comment]
I narrowed it down to this part:
```
<mover>
  <mspace height='1em'/>
  <mn>6</mn>
</mover>
```
The cleanup removed the `mspace` which it shouldn't have done because `mover` requires two children.

A fix is pending.

**Comment by mwhapples** [comment]
Thanks for looking at this one, sorry I wasn't able to reduce the MathML expression to the minimum myself.
